### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by MichiFr** [c0d3z3r0/rbmode#1]
Hi Michael,

I would like to switch the LAN/WAN mode to universal on a Riverbed Steelhead server that does not have any possibility to attach a monitor running a full Linux live system.

That means I've to use the serial console but don't actually have any (Linux) OS installed to follow your installation instructions.

What's the best way to get this task running? Any recommendations for a tiny, serial console, Linux live system that can use one of the available LAN ports to connect to the internet and download your scripts?

Or with other words: how did you manage to switch the mode on that piece of hardware?

You can answer in German language as well - I'm German ^^ 

Thanks,
Michael

**Comment by c0d3z3r0** [comment]
- https://github.com/ffries/Debian-installer-with-serial-console
- https://github.com/telegrapher/debian-over-serial-port-howto
- ...
